#!/usr/bin/env python3
"""Build coost through the Crust C++ subset.

The whole library is lowered as ONE translation unit: every source in
SOURCES is spliced into build/co_all.cc, lowered by crust's cpprust.py to
build/co.c, then compiled by a C compiler. That is how Crust consumes C++
(one unit, no link boundary), and it means one cpprust run per build.

    python3 build.py            # build/co.c and build/co.o
    python3 build.py test       # also lower, compile and run tests/*.cc
    python3 build.py cxx        # cross-check: compile the same sources with g++
    python3 build.py clean

Environment: CRUST (path to the crust checkout, default ../crust),
CC (default cc), CXX (default g++), ASAN=1 (tests under ASan/UBSan).
"""
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.join(ROOT, "build")
INCLUDE = os.path.join(ROOT, "include")
CRUST = os.environ.get("CRUST", os.path.join(ROOT, "..", "crust"))
CPPRUST = os.path.join(CRUST, "tools", "cpprust.py")
CC = os.environ.get("CC", "cc")
CXX = os.environ.get("CXX", "g++")

# Order matters only for readability of the generated C.
SOURCES = [
    "src/mem.cc",
    "src/fast.cc",
    "src/fastring.cc",
    "src/str.cc",
    "src/path.cc",
    "src/time.cc",
    "src/fs.cc",
    "src/json.cc",
    "src/hash/murmur_hash.cc",
    "src/hash/crc16.cc",
    "src/hash/md5.cc",
    "src/hash/sha256.cc",
    "src/hash/base64.cc",
    "src/hash/url.cc",
]

CFLAGS = ["-std=gnu11", "-O2", "-Wall", "-Wno-unused-function"]
if os.environ.get("ASAN"):
    CFLAGS += ["-g", "-fsanitize=address,undefined"]
CXXFLAGS = ["-std=c++11", "-O2", "-Wall", "-D_GNU_SOURCE"]


def run(cmd):
    print("  " + " ".join(os.path.relpath(c, ROOT) if c.startswith(ROOT) else c
                          for c in cmd))
    r = subprocess.run(cmd)
    if r.returncode != 0:
        sys.exit(r.returncode)


def unity(path, extra=()):
    """Write a .cc that includes every library source, then `extra`."""
    with open(path, "w") as f:
        f.write("/* generated by build.py -- do not edit */\n")
        for s in list(SOURCES) + list(extra):
            f.write('#include "%s"\n' % os.path.relpath(os.path.join(ROOT, s), BUILD))


def lower(src, out):
    if not os.path.exists(CPPRUST):
        sys.exit("cpprust.py not found at %s (set CRUST=/path/to/crust)" % CPPRUST)
    run([sys.executable, CPPRUST, src, "-o", out, "--incdir", INCLUDE,
         "-D", "CO_CRUST", "--no-clang"])
    # headers are spliced into one file, so their include guards are noise
    with open(out) as f:
        text = f.read()
    with open(out, "w") as f:
        f.write(text.replace("#pragma once\n", ""))


def build():
    os.makedirs(BUILD, exist_ok=True)
    src = os.path.join(BUILD, "co_all.cc")
    unity(src)
    lower(src, os.path.join(BUILD, "co.c"))
    run([CC] + CFLAGS + ["-c", os.path.join(BUILD, "co.c"),
                         "-o", os.path.join(BUILD, "co.o")])


def tests():
    d = os.path.join(ROOT, "tests")
    names = sorted(n for n in os.listdir(d) if n.endswith(".cc")) if os.path.isdir(d) else []
    failed = []
    for n in names:
        base = n[:-3]
        src = os.path.join(BUILD, base + "_all.cc")
        c = os.path.join(BUILD, base + ".c")
        exe = os.path.join(BUILD, base)
        unity(src, ["tests/" + n])
        lower(src, c)
        run([CC] + CFLAGS + [c, "-o", exe, "-lm"])
        print("  ./" + os.path.relpath(exe, ROOT))
        if subprocess.run([exe]).returncode != 0:
            failed.append(n)
    if failed:
        sys.exit("FAILED: " + " ".join(failed))
    print("all %d test(s) passed" % len(names))


def cxx():
    """Compile the same sources as C++ -- catches mistakes the lowering
    would carry through silently."""
    os.makedirs(BUILD, exist_ok=True)
    d = os.path.join(ROOT, "tests")
    names = sorted(n for n in os.listdir(d) if n.endswith(".cc")) if os.path.isdir(d) else []
    for n in names:
        base = n[:-3]
        src = os.path.join(BUILD, base + "_all.cc")
        exe = os.path.join(BUILD, base + "_cxx")
        unity(src, ["tests/" + n])
        run([CXX] + CXXFLAGS + ["-I", INCLUDE, src, "-o", exe])
        print("  ./" + os.path.relpath(exe, ROOT))
        if subprocess.run([exe]).returncode != 0:
            sys.exit("FAILED (c++): " + n)


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    if cmd == "clean":
        shutil.rmtree(BUILD, ignore_errors=True)
    elif cmd == "build":
        build()
    elif cmd == "test":
        build()
        tests()
    elif cmd == "cxx":
        cxx()
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
